name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
      - GCP_dependency_workflow
    paths:
      - 'docker/**'
      - 'create_ringtone.py'
      - 'sample_speaker.py'
      - 'generate_script.py'
      - 'utils.py'
      - 'requirements.txt'
      - '.github/workflows/docker_image_GHCR.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/create-ringtone
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/create_ringtone.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CA_KEY }} # Spelling mistake... :/

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy create-ringtone \
            --image europe-north2-docker.pkg.dev/ringtonechanger-494218/ghcr-mirror/viktis1/create-ringtone:latest \
            --service-account ghcr-puller@ringtonechanger-494218.iam.gserviceaccount.com \
            --region europe-north2 \
            --memory 24Gi \
            --cpu 6 \
            --timeout 3600 \
            --set-env-vars GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
            --no-allow-unauthenticated \
            --quiet
            # --gpu nvidia-l4 \
            # --gpu-count 1 \ 
            
            
            
